name: Machine Learning CI Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/anhartamim36/Workflow_CI_Muhammad-Anhar-Tamim.mlflow"
  MLFLOW_TRACKING_USERNAME: "anhartamim36"
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Base Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "mlflow==2.19.0" dagshub setuptools scikit-learn pandas matplotlib joblib

    - name: Run Model Retraining
      run: |
        cd MLProject
        # Menjalankan script secara langsung setelah auth dagshub
        python -c "import dagshub; dagshub.init('Workflow_CI_Muhammad-Anhar-Tamim', 'anhartamim36', mlflow=True)"
        python modelling.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tmmanhar
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image using MLflow
      run: |
        RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('$MLFLOW_TRACKING_URI'); runs = mlflow.search_runs(experiment_names=['MSML_Breast_Cancer_Basic']); print(runs.iloc[0].run_id)")
        
        echo "Building Docker Image for RUN_ID: $RUN_ID"
        
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "tmmanhar/breast-cancer-model:latest" \
          --enable-mlserver

    - name: Push Docker Image to Docker Hub
      run: |
        docker push tmmanhar/breast-cancer-model:latest